### ISSUE TITLE
Better error message when no CMS command provided

### ISSUE THREAD

**Issue by JiriKalvoda** [kasiopea-org/pisek#180]

**Comment by JiriKalvoda** [comment]
```
cmsuser@contest:[~/cms-venv]~/ceoi-2024/tasks/...(....)
$ pisek cms
2024-06-16 14:21:02,121 - INFO [<unknown>] Using configuration file /home/cmsuser/cms-git/config/cms.conf.
Traceback (most recent call last):
  File "/home/cmsuser/cms-venv/bin/pisek", line 8, in <module>
    sys.exit(main_wrapped())
             ^^^^^^^^^^^^^^
  File "/home/cmsuser/pisek/pisek/__main__.py", line 406, in main_wrapped
    result = main(sys.argv[1:])
             ^^^^^^^^^^^^^^^^^^
  File "/home/cmsuser/pisek/pisek/__main__.py", line 390, in main
    raise RuntimeError(f"Unknown CMS command {args.cms_subcommand}")
RuntimeError: Unknown CMS command None
```

Tohle by mohlo spadnout trošku hezceji.
